sudo: required
dist: trusty
language: php
php:
    - 7
    - 7.1
    - 7.2
    - 7.3

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

env:
    global:
        - CORE_BRANCH=master
        - DB=mysql

matrix:
    include:
        - php: 7.1
          env: CORE_BRANCH=stable15
        - php: 7.0
          env: CORE_BRANCH=stable14
        - php: 5.6
          env: CORE_BRANCH=stable13
        - php: 5.6
          env: CORE_BRANCH=stable12
    fast_finish: true

before_install:
    # download custom version of phpunit
    - cd ../../
    - wget https://phar.phpunit.de/phpunit-5.7.phar
    - chmod +x phpunit-5.7.phar
    - mkdir bin
    - sudo mv phpunit-5.7.phar bin/phpunit
    - export PATH="$PWD/bin:$PATH"
    # install core
    - cd georgehrke
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH nextcloud
    - mv telephoneprovider nextcloud/apps/

before_script:
    - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
    - cd nextcloud
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable telephoneprovider
    - php -S localhost:8080 &
    - cd apps/telephoneprovider

script:
    - make test

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/php-unit.clover

after_failure:
    - cat ../../data/nextcloud.log
